# Atividade 4
## Grupo 3

In [5]:
import numpy as np
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_excel('2025 2ºsem M109 Cell Phone Dependence Scale.xlsx')
df.columns = df.columns.str.strip()
df.head()

ID      Sexo:  Idade (anos):  Peso (kg):  Altura (m):    Coluna1  \
0   2  Masculino             18        73.0         1.84  21.561909   
1   3  Masculino             18        75.0         1.75  24.489796   
2   4   Feminino             22        67.0         1.73  22.386314   
3   5  Masculino             20        85.0         1.82  25.661152   
4   6  Masculino             19        64.0         1.90  17.728532   

                           Curso: Período: Turno de estudo:  \
0        Engenharia de Computação       P3         Integral   
1          Engenharia de Software       P3         Integral   
2          Engenharia de Software       P9          Noturno   
3        Engenharia de Computação       P6         Integral   
4  Engenharia de Telecomunicações       P5         Integral   

  Faz alguma atividade extraclasse. se sim qual (is)?  ...  \
0                             Iniciação Científica ;   ...   
1                                            Outros;   ...   
2                               Monitoria ;Estágio ;   ...   
3                                         Trabalho ;   ...   
4                             Iniciação Científica ;   ...   

  13- Com que frequência você se mantém conectado   ao celular quando está com amigos ou família?  \
0                                     Frequentemente                                                
1                                     Frequentemente                                                
2                                     Frequentemente                                                
3                                  Nunca / Raramente                                                
4                                  Nunca / Raramente                                                

  Pontos 13  \
0         1   
1         1   
2         1   
3         0   
4         0   

  14- Com que frequência você se sente sozinho se não participa de redes sociais ou quando não está em grupo enquanto outros estão?  \
0                                  Nunca / Raramente                                                                                  
1                                     Frequentemente                                                                                  
2                                  Nunca / Raramente                                                                                  
3                                  Nunca / Raramente                                                                                  
4                                  Nunca / Raramente                                                                                  

  Pontos 14  \
0         0   
1         1   
2         0   
3         0   
4         0   

  15- Quantas vezes  você mantém na agenda do celular o número de um médico. psicólogo ou hospital por medo de se sentir mal na rua?  \
0                                     Frequentemente                                                                                   
1                                             Sempre                                                                                   
2                                     Frequentemente                                                                                   
3                                  Nunca / Raramente                                                                                   
4                                  Nunca / Raramente                                                                                   

  Pontos 15 16- Com que frequência você toca no celular?  Pontos 16  \
0         1                                       Sempre          2   
1         2                                       Sempre          2   
2         1                            Nunca / Raramente          0   
3         0                               Frequentemente          1   
4         0                               Frequentem

In [7]:
colunas_pontos = [f"Pontos {i}" for i in range(1, 17)]
df["Pontuação final"] = df[colunas_pontos].sum(axis=1)

def classificar(pontuacao):
    if pontuacao <= 10:
        return "Leve"
    elif pontuacao <= 20:
        return "Moderado"
    else:
        return "Grave"
    
df["Classificação"] = df["Pontuação final"].apply(classificar)

### 1) Mostre as hipóteses

- Hipótese nula (H₀): As variáveis "Moradia" e "Dependência" são interdependentes. 

> A dependência em smartphones é independente da condição de moradia.
Ou seja, morar sozinho ou com outras pessoas não altera o nível de dependência em smartphones.

- Hipótese alternativa (H₁): As variáveis "Moradia" e "Dependência" não são dependentes.

> A dependência em smartphones depende da condição de moradia.
Ou seja, existe uma relação significativa entre a condição de moradia e o nível de dependência em smartphones.

### 2) Faça print dos cálculos realizados (pode usar qualquer software para os cálculos).

In [10]:
dados = df[["Com quem mora:", "Classificação"]].copy()
tabela_contingencia = pd.crosstab(dados["Com quem mora:"], dados["Classificação"])

tabela_contingencia.head()

Classificação   Grave  Leve  Moderado
Com quem mora:                       
Amigos/colegas     15     8        35
Familiares         18    24        41
Outros              2     1        10
Sozinho             6    14        50

In [12]:
from scipy.stats import chi2_contingency

qui2, p_valor, gl, esperados = chi2_contingency(tabela_contingencia)
print(f"Qui-quadrado: {qui2:.4f}")
print(f"p-valor: {p_valor:.4f}")
print(f"Graus de liberdade: {gl}")

Qui-quadrado: 14.6952
p-valor: 0.0228
Graus de liberdade: 6


### 3)  Coloque a decisão estatística.

Como o p-valor (0.0228) < 0.05, rejeita-se H₀.

Portanto, há evidências estatisticamente significativas de que o tipo de moradia influencia o nível de dependência em smartphones.

### 4) Elabore uma conclusão.

O teste do Qui-quadrado de independência indica uma associação significativa entre o tipo de moradia e o nível de dependência em smartphones (χ² = 14.6952; gl = 6; p = 0.0228).
Assim, o padrão de dependência não é o mesmo para quem mora sozinho e para quem mora com outras pessoas, sugerindo que o contexto de moradia pode estar relacionado ao grau de uso e dependência do celular.

In [ ]:
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors

# Dados do teste
qui2 = 14.6952
p_valor = 0.0228
gl = 6
alpha = 0.05

# Criação do PDF
pdf_filename = "Atividade5_Grupo3.pdf"
doc = SimpleDocTemplate(pdf_filename, pagesize=A4)
styles = getSampleStyleSheet()
elements = []

# Cabeçalho
titulo = Paragraph("<b>Atividade 5 – Testes Categorizados</b>", styles["Title"])
subtitulo = Paragraph("Grupo 3 – Relação entre Moradia e Dependência em Smartphones", styles["Heading2"])
elements += [titulo, subtitulo, Spacer(1, 12)]

# Seção: Hipóteses
texto_hipoteses = """
<b>Hipóteses:</b><br/>
H0: Não existe associação entre o tipo de moradia e o nível de dependência em smartphones.<br/>
H1: Existe associação entre o tipo de moradia e o nível de dependência em smartphones.<br/>
Nível de significância: α = 0,05
"""
elements += [Paragraph(texto_hipoteses, styles["Normal"]), Spacer(1, 12)]

# Seção: Resultados
data_resultados = [
    ["Estatística", "Valor"],
    ["Qui-quadrado (χ²)", f"{qui2:.4f}"],
    ["Graus de liberdade (gl)", f"{gl}"],
    ["p-valor", f"{p_valor:.4f}"],
    ["Nível de significância (α)", f"{alpha:.2f}"]
]
tabela = Table(data_resultados, hAlign="LEFT")
tabela.setStyle(TableStyle([
    ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
    ("TEXTCOLOR", (0,0), (-1,0), colors.black),
    ("GRID", (0,0), (-1,-1), 0.5, colors.black),
    ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
]))
elements += [Paragraph("<b>Resultados do Teste Qui-quadrado:</b>", styles["Heading3"]), tabela, Spacer(1, 12)]

# Seção: Decisão
if p_valor <= alpha:
    decisao = "Como p-valor < 0,05, rejeita-se H0. Existe associação significativa entre as variáveis."
else:
    decisao = "Como p-valor > 0,05, não se rejeita H0. Não há associação significativa entre as variáveis."
elements += [Paragraph(f"<b>Decisão estatística:</b> {decisao}", styles["Normal"]), Spacer(1, 12)]

# Seção: Conclusão
conclusao = """
<b>Conclusão:</b><br/>
O teste do Qui-quadrado de independência (χ² = 14,6952; gl = 6; p = 0,0228) indica que há associação significativa entre o tipo de moradia e o nível de dependência em smartphones.
Isso sugere que o padrão de dependência não é o mesmo entre quem mora sozinho e quem mora com outras pessoas,
indicando que o contexto de moradia pode influenciar o grau de uso e dependência do celular.
"""
elements += [Paragraph(conclusao, styles["Normal"])]

# Geração do PDF
doc.build(elements)

Relatório gerado com sucesso: Atividade5_Grupo3.pdf
